title: Hey this is Rahul
description: Entrepreneur | Engineer | Artist 
url: "http://www.rahulnayak.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Rahul Nayak # add your name
author-img: rahulnayak_vector400.jpg # add your photo
author-img: rahulnayak_vector400.jpg # add your photo
about-author: Engineer, Artist, Science enthusiast, Traveller and a lifelong scholar. 
twitter: rahulnyk # add your Twitter handle
youtube: https://www.youtube.com/user/aihikii
fivehundredpx: rahulnayak #TODO 500px account has to be added here
medium: https://medium.com/@rahul.nyk #TODO medium account has to be added here
facebook: rahul.nyk # add your Facebook handle
github:  # add your Github handle
linkedin: rahulnyk # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: rahulnyk # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
