title: Hello, world! I'm Rahul Nayak
description: > # this means to ignore newlines until "baseurl:"
  This is a test description for my site. I am Rahul Nayak
url: "http://www.rahulnayak.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Rahul Nayak # add your name
author-img: rahulnayak_vector400.jpg # add your photo
author-img: rahulnayak_vector400.jpg # add your photo
about-author: I am an engineer, an artist, a science enthusiast and a lifelong scholar. 
twitter: # add your Twitter handle
500px: #TODO 500px account has to be added here
medium: #TODO medium account has to be added here
facebook: rahul.nyk # add your Facebook handle
github:  # add your Github handle
linkedin: rahulnyk # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: rahulnyk # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
