title: Hello, world! I'm Rahul Nayak
description: > # this means to ignore newlines until "baseurl:"
  This is a test description for my site. I am Rahul Nayak
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Rahul Nayak # add your name
author-img: rahulnayak_vector400.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: artemsheludko # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: rahulnyk # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
